permissionset 99921 GeneratedPermission
{
    Assignable = true;
    Permissions = tabledata "LC Amended Details"=RIMD,
        tabledata "LC Bank Limit Details"=RIMD,
        tabledata "LC Detail"=RIMD,
        tabledata "LC Orders"=RIMD,
        tabledata "LC Register"=RIMD,
        tabledata "LC Setup"=RIMD,
        tabledata "LC Terms"=RIMD,
        table "LC Amended Details"=X,
        table "LC Bank Limit Details"=X,
        table "LC Detail"=X,
        table "LC Orders"=X,
        table "LC Register"=X,
        table "LC Setup"=X,
        table "LC Terms"=X,
        report "Close LC"=X,
        report "LC Amendments"=X,
        report "LC Utilisations"=X,
        report "Pending LC's"=X,
        report "Renewal of LC's Credit Limit"=X,
        codeunit "Letter of Credit"=X,
        page "LC Amended Details"=X,
        page "LC Amended List"=X,
        page "LC Bank Limit Details"=X,
        page "LC Detail"=X,
        page "LC Detail List"=X,
        page "LC Journal"=X,
        page "LC Orders"=X,
        page "LC Register"=X,
        page "LC Setup"=X,
        page "LC Terms"=X;
}